name: Parametros-Agendamento
values:
  - key: servidor
    value: 'http://localhost:8081'
    enabled: true
  - key: estabelecimento_id
    value: ''
    enabled: true
  - key: profissional_id
    value: ''
    enabled: true
  - key: servico_id
    value: ''
    enabled: true
  - key: especialidade_id
    value: ''
    enabled: true
  - key: cliente_id
    value: '55555555-5555-5555-5555-555555555555'
    enabled: true
